[package]
name = "rayon_tutorial"
version = "0.1.0"
authors = []
edition = "2021"

[dependencies]
aes = "0.8.4"
cipher = "0.4.4"
ctr = "0.9.2"
data-encoding = "2.10.0"
getrandom = "0.3.4"
proptest = "1.9.0"
rayon = "1.11.0"
rs_merkle = "1.5.0"
thiserror = "2.0.17"

